"""HTML summary for complete public-dataset runs; no synthetic scoring substitution."""
import argparse, html, json, os, sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from scripts.tune_dense_detection import read,write
from scripts.benchmark_public import MODES

def table(head,rows):return '<div class="scroll"><table><thead><tr>'+''.join('<th>'+html.escape(h)+'</th>' for h in head)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+str(c)+'</td>' for c in row)+'</tr>' for row in rows)+'</tbody></table></div>'
def pct(v):return f'{v*100:.2f}'
def metrics(row):
    m=row['metrics']
    return [m[k] for k in (['Det-Recall','Det-Precision','Det-Fscore','E2E-Recall','E2E-Precision','E2E-Fscore'] if row['dataset']=='hiertext' else ['detection_recall','detection_precision','detection_f1','end_to_end_recall','end_to_end_precision','end_to_end_f1'])]
def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--root',type=Path,default=ROOT/'pybaseline/results/public_v1');a=p.parse_args();out=a.root;parts=['<h1>Public labelled OCR comparison</h1><p>Frozen test splits, original image pixels, DB ResNet34 + PARSeq FP32. No tuning on these test pages. Rust plain and Python plain use the same resolution; Python rotated enables stock page straightening and crop orientation. Rust enhanced enables page orientation, fractional deskew, dense refinement and thin-character recovery. The enhanced methods have different capabilities; they are not a pure language-runtime comparison. Known stock docTR negative-stride crop exceptions are recorded per page with empty predictions: failed pages remain in the denominator, and the Failures column must be considered alongside scores. No crop workaround was applied to the stock rows. The separately named python_rotated_copy_1536 diagnostic reruns failed pages after copying recognition crop arrays to positive-stride storage. Pixel values and OCR rules stay unchanged; three previously successful controls per dataset are checked. Successful original pages are reused, so this diagnostic has no throughput figure.</p>'];all_rows=[]
    parts.append('<h2>Findings</h2><p>All 1,784 test images completed across six configurations. Plain Rust closely matches Python accuracy at each resolution. On HierText, observed plain throughput was 12.43 vs 7.50 pages/s at 1024 and 8.40 vs 5.31 at 1536. This compares Rust/ONNX Runtime with Python/PyTorch, so the difference cannot be attributed to the language alone.</p><p>Higher resolution helps FUNSD slightly and HierText substantially, but hurts CORD. The Rust enhancement bundle lowers end-to-end F1 on every dataset relative to plain Rust at 1536. Python rotation with the separate array-copy compatibility fix reaches 48.90% on HierText, above Rust enhanced at 42.32%. Keep enhancements opt-in; isolate orientation, deskew and refinement on development splits before changing defaults.</p><p>Thin recovery adds 39 predictions across all test images: only four match the public labels under the coverage check, and three meet strict IoU matching. Missing annotations can explain some mismatches, but this does not validate enabling recovery generally.</p>')
    for dataset in ['funsd','cord-v2','hiertext']:
        manifest=ROOT/'testdata/public'/dataset/'prepared/manifest.json';pages=read(manifest);rows=[];resources=[];diagnostics=[];adds=[];modes={}
        for mode in MODES+["python_rotated_copy_1536"]:
            folder=out/dataset/mode
            if not (folder/'scores.json').exists():continue
            score=read(folder/'scores.json');summary=read(folder/'summary.json');modes[mode]=score
            rows.append([mode,score['pages'],len(summary.get('failed_pages',[])),*[pct(v) for v in metrics(score)]]);r=summary['resources']
            gib=lambda x:f'{x/2**30:.2f}' if x is not None else 'unavailable'
            resources.append([mode,f"{summary['wall_seconds']:.1f}" if summary.get("wall_seconds") is not None else "n/a",f"{summary['pages_per_second']:.3f}" if summary.get("pages_per_second") is not None else "n/a",gib(r.get('device_vram_bytes_max')),gib(r.get('vram_increment_peak_bytes'))])
            for group in ['single','single_digit','I']:
                c=score['groups'][group];diagnostics.append([mode,group,c['truth'],c['detected'],c['exact'],c['no_overlap']])
            rr=score['recovered'];adds.append([mode,rr['total'],rr['correct_coverage'],rr['strict_exact']]);all_rows.append(dict(dataset=dataset,mode=mode,scores=score,summary=summary))
        total=sum(len(p['words']) for p in pages);legible=sum(sum(not w.get('ignore') for w in p['words']) for p in pages)
        parts.append(f'<h2>{dataset}</h2><p>{len(pages):,} test images; {total:,} labelled words; {legible:,} evaluable words.</p>')
        parts.append('<p>'+('Official HierText polygon evaluator, pinned upstream revision 70b6620; exact case-sensitive text; illegible regions ignored using upstream overlap rules. Continuous polygons, no downsampling.' if dataset=='hiertext' else 'docTR LocalizationConfusion and OCRMetric, IoU ≥0.5, exact case-sensitive text. Axis envelopes match the published-style box setup; polygon scores are retained separately in scores.json.')+'</p>')
        parts.append(table(['Mode','Pages','Failures','Det recall %','Det precision %','Det F1 %','OCR recall %','OCR precision %','OCR F1 %'],rows))
        if dataset!='hiertext':parts.append('<details><summary>Strict polygon scores</summary>'+table(['Mode','Det F1 %','OCR F1 %'],[[mode,pct(s['polygons']['detection_f1']),pct(s['polygons']['end_to_end_f1'])] for mode,s in modes.items()])+'</details>')
        parts.append('<h3>Short-word diagnostics</h3><p>Polygon matching at IoU ≥0.5, with ignored-region predictions removed. This diagnostic uses assignment matching; HierText’s official aggregate uses mutual-best matching. “No overlap” means no predicted box touches the labelled word.</p>'+table(['Mode','Group','Labelled','Detected','Exact','No overlap'],diagnostics))
        parts.append('<h3>Thin recovery additions</h3><p>Coverage verification requires correct text and ≥50% coverage of exactly one label. The strict column additionally requires IoU ≥0.5. Inspect failures against the original image because public annotations can omit visible text.</p>'+table(['Mode','Added','Verified by coverage','Strict exact'],adds))
        parts.append('<h3>Observed runtime and GPU memory</h3><p>Model loading and full-corpus warmup excluded; decode and result output included. One run per mode; downloads and scoring may overlap. These are diagnostic timings, not a controlled speedup claim. Total VRAM includes the desktop; incremental peak includes loading and warmup relative to pre-load idle.</p>'+table(['Mode','Seconds','Pages/s','Device peak GiB','Increment peak GiB'],resources))
        parts.append('<p>Evidence: '+ ' · '.join(f'<a href="{dataset}/{mode}/scores.json">{mode}</a>' for mode in modes)+'</p>')
        enhanced=out/dataset/'rust_enhanced_1536'
        if (enhanced/'recovered.json').exists():
            recovered=read(enhanced/'recovered.json');by_id={p['id']:p for p in pages};suspect=[r for r in recovered if not r['correct_coverage']]
            parts.append('<details><summary>Recovery additions requiring review ('+str(len(suspect))+')</summary><div class="cards">')
            for r in suspect[:24]:
                p=by_id[r['page']];W,H=p['width'],p['height'];coords=r['polygon'];xx=[v[0]*W for v in coords];yy=[v[1]*H for v in coords];x=max(0,min(xx)-70);y=max(0,min(yy)-25);w=min(W-x,max(xx)-min(xx)+140);h=min(H-y,max(yy)-min(yy)+50);src=html.escape(os.path.relpath(p['image'],out).replace(os.sep,'/'),quote=True);points=' '.join(f'{a*W},{b*H}' for a,b in coords)
                parts.append(f'<div class="card"><b>{html.escape(r["text"])}</b> / {html.escape(r["page"])}<br>Labels: {html.escape(str(r["truth"]))}<svg viewBox="{x} {y} {w} {h}"><image href="{src}" width="{W}" height="{H}"/><polygon points="{points}" fill="none" stroke="#cf6419" stroke-width="2"/></svg></div>')
            parts.append('</div></details>')
    parts.append('''<h2>Published reference scores</h2><p>docTR reports DB ResNet34 detection recall/precision of 82.76/76.75% on FUNSD and 89.20/71.74% on CORD. Its published end-to-end DB ResNet50 + PARSeq recall/precision is 73.52/76.27% and 85.91/80.13%, respectively. Those figures combine train and evaluation splits; our rows above are test-only. Our CORD v2 labels and docTR 1.1.0 checkpoints also prevent treating differences as a reproduced improvement over the published table. The ResNet50 end-to-end row is a different detector. <a href="https://mindee.github.io/doctr/latest/using_doctr/using_models.html">docTR source</a>.</p><p>On HierText’s same 1,634-image test split, the 2023 competition reported end-to-end F1 of 79.58% for Upstage KR and 71.64% for DBNet++ + SATRN. These are benchmark context, not matched-weight comparisons: those systems were developed/trained for the competition. Our public test runs do not train or fine-tune the models. <a href="https://arxiv.org/pdf/2305.09750">Competition report, Table 2</a>.</p><p>Recognition-only published scores assume supplied word crops and must not be compared with our whole-page OCR scores. The downloaded training/development splits are retained separately for future work. Known checkpoint training overlap has not been established here.</p>''')
    parts.append('<p><a href="resolution_example.html">Visual example: CORD resolution regression</a> · <a href="evaluator_validation.json">Official evaluator reproduction</a> · <a href="results.json">All scores and run metadata</a> · <a href="download_inventory.json">Download inventory</a></p>')
    write(out/'results.json',all_rows)
    (out/'report.html').write_text('<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Public OCR benchmarks</title><style>body{font:16px system-ui;max-width:1450px;margin:30px auto;padding:0 20px;color:#203247}p{line-height:1.5}table{border-collapse:collapse;width:100%}td,th{padding:9px;border:1px solid #ccd;text-align:left}th{background:#e1edf5}.scroll{overflow:auto}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:12px}.card{min-width:0;border:1px solid #ccd;padding:10px;overflow-wrap:anywhere}svg{width:100%;height:130px}summary{cursor:pointer;margin:12px 0}h2{margin-top:40px}</style>'+''.join(parts),encoding='utf-8');print(out/'report.html')
if __name__=='__main__':main()
