from pathlib import Path
from typing import Any, Iterator, Mapping
__version__: str

def default_config(profile: str = "balanced") -> dict[str, Any]: ...
class Stream(Iterator[dict[str, Any]]):
    config: dict[str, Any]
    def __init__(self, models: str | Path = "models", config: Mapping[str, Any] | str | Path | None = None) -> None: ...
    def submit_rgb(self, id: str, width: int, height: int, data: bytes) -> None: ...
    def finish_input(self) -> None: ...
    def __iter__(self) -> Stream: ...
    def __next__(self) -> dict[str, Any]: ...
    @property
    def stats(self) -> dict[str, Any]: ...
    def close(self) -> None: ...
    def __enter__(self) -> Stream: ...
    def __exit__(self, *exc: Any) -> None: ...
